[package]
name = "rust-beginner"
version = "0.1.0"
authors = ["Reza Indra <dev.rezaindra@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
